sudo: required
dist: xenial
env:
  global: []
  matrix:
  - CFG=defconfig VER=v4.17
  - CFG=defconfig VER=v4.18
  - CFG=defconfig VER=v4.19
  - CFG=defconfig VER=v4.20

matrix:
  allow_failures: []

notifications:
  email: false
before_script:
- sudo apt update &>/dev/null
- sudo apt install gcc -y -qq &>/dev/null || true
- wget https://github.com/torvalds/linux/archive/$VER.zip -qO linux.zip
- unzip linux.zip &>/dev/null
- cd linux-${VER##v}
script:
- make $CFG
- make
